version: "3.7"
services:
  mongo:
    image: mongo:4.2
    container_name: "library-mongo"
    volumes:
    - library_mdata_volume:/data/db
    ports:
        - 27017:27017
    command: [mongod]

volumes:
  library_mdata_volume:
    driver: local  # is already local by default


